name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v1
      with:
        cmake-version: '3.10'

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: ctest -C Release --output-on-failure

    - name: Install ncurses
      run: sudo apt-get install libncurses-dev

    - name: Run main.cpp
      run: ./build/main
